### ISSUE TITLE
[New rules request][AUTO] tv.danmaku.bili

### ISSUE THREAD

**Issue by sjdhome** [RikkaW/RedirectStorage-rules#157]
## Application information
 - Package name: `tv.danmaku.bili`
 - Display name: 哔哩哔哩
 - Version: 5.21.0 (5210000)
 ## User rules
 - `recommended`: Yes
 - `need_appops`: Yes
 - `feature_affected`: No
 ### ObserverInfo
 #### Directory: `Android/data/tv.danmaku.bili/download`
 - `description`: `保存的视频`

 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_CN_#Hans
 - Storage Redirect app version: 0.8.0-alpha.r201.af9d5c8 (201)
 ## JSON Output
 ```
 {
     "package": "tv.danmaku.bili",
     "recommended": true,
     "need_appops": true,
     "feature_affected": false,
     "authors": [],
     "observers": [
         {
             "description": "保存的视频",
             "source": "Android/data/tv.danmaku.bili/download"
         }
     ]
 }
 ```

**Comment by simonsmh** [comment]
不需要的吧
blv格式本来就不给用户用的

**Comment by RikkaW** [comment]
不需要 而且似乎也不会乱吐文件（
