### ISSUE TITLE
Add Refresh function

### ISSUE THREAD

**Issue by EraserKing** [RikkaW/RedirectStorage-rules#189]
Would you like to add Refresh option into the menu?
I'd like to see how many folders / files have been redirected (to see if the redirection works for an app), but I always need to exit the app and relaunch it.

**Comment by RikkaW** [comment]
For now, refreshing redirected files count is executed when `onBindViewHolder` called and has a 10 sec minimum interval, so you can scroll down, wait and scroll up (to make views be re-bound), the count should be refreshed.
(Refresh will be added in next version.)

**Comment by EraserKing** [comment]
Got it. Thanks.
