### ISSUE TITLE
Duplicated Android/data in path

### ISSUE THREAD

**Issue by EraserKing** [RikkaW/RedirectStorage-rules#190]
If an app originally intends to write to /sdcard/Android/data/<package name>, and it's redirected, then it's redirected to /sdcard/Android/data/<package name>/storage/Android/data/<package name>

I'm wondering if this is intended behavior, or we should skip redirecting paths into /sdcard/Android/data/<package name>.

**Comment by RikkaW** [comment]
It's an intended behavior. Current implementation is change return value of `StorageManagerService#getVolumeList`, it's impossible to redirect a specific folder.

**Comment by EraserKing** [comment]
Thanks.
I read the source code of that method and find no place to predict the way the folder to write into.
Closing.
