### ISSUE TITLE
[New rules request][AUTO] com.android.chrome

### ISSUE THREAD

**Issue by sjdhome** [RikkaW/RedirectStorage-rules#195]
## Application information
 - Package name: `com.android.chrome`
 - Display name: Chrome
 - Version: 63.0.3239.111 (323911152)
 ## User rules
 - `recommended`: Yes
 - `need_appops`: No
 - `feature_affected`: No
 ### ObserverInfo
 #### Directory: `Download`
 - `description`: `保存的文件`

 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_CN_#Hans
 - Storage Redirect app version: 0.8.0-alpha.r201.af9d5c8 (201)
 ## JSON Output
 ```
 {
     "package": "com.android.chrome",
     "recommended": true,
     "need_appops": false,
     "feature_affected": false,
     "authors": [],
     "observers": [
         {
             "description": "保存的文件",
             "source": "Download"
         }
     ]
 }
 ```

**Comment by fython** [comment]
@RikkaW Should we enable redirecting for Google Chrome?

**Comment by sjdhome** [comment]
Chrome作为webview使用很容易积聚垃圾文件的..

**Comment by RikkaW** [comment]
Files created by Chrome are all stored in correct place.
