### ISSUE TITLE
[New rules request][AUTO] de.robv.android.xposed.installer

### ISSUE THREAD

**Issue by monkey-sking** [RikkaW/RedirectStorage-rules#203]
## Application information
 - Package name: `de.robv.android.xposed.installer`
 - Display name: Xposed Installer
 - Version: 3.1.4 (42)
 ## User rules
 - `recommended`: No
 - `need_appops`: No
 - `feature_affected`: No
 ### ObserverInfo
 #### Directory: `Android/data/de.robv.android.xposed.installer/cache/downloads`
 - `description`: `下载的软件`

 ## More information
 - Android version: 8.0.0 (API 26)
 - User language: zh_CN_#Hans
 - Storage Redirect app version: 0.8.0-alpha.r211.4cf3c2f (211)
 ## JSON Output
 ```
 {
     "package": "de.robv.android.xposed.installer",
     "recommended": false,
     "need_appops": false,
     "feature_affected": false,
     "authors": [],
     "observers": [
         {
             "description": "下载的软件",
             "source": "Android/data/de.robv.android.xposed.installer/cache/downloads"
         }
     ]
 }
 ```

**Comment by RikkaW** [comment]
不可以乱写
