### ISSUE TITLE
[New rules request][AUTO] de.robv.android.xposed.installer

### ISSUE THREAD

**Issue by DaXiaBinge** [RikkaW/RedirectStorage-rules#222]
## Application information
 - Package name: `de.robv.android.xposed.installer`
 - Display name: Xposed Installer
 - Version: 3.1.5 (43)
 ## User rules
 - `recommended`: No
 - `need_appops`: No
 - `feature_affected`: Yes
 - Reason: <p dir="ltr">&#37325;&#23450;&#21521;&#21518;&#19979;&#36733;&#38378;&#36864;</p>

 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.1.1 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.9.0-alpha.r274.8423e60 (274)
 ## JSON Output
 ```
 {
     "package": "de.robv.android.xposed.installer",
     "recommended": false,
     "need_appops": false,
     "feature_affected": true,
     "authors": ["DaXiaBinge"],
     "reason": {"default": "<p dir="ltr">&#37325;&#23450;&#21521;&#21518;&#19979;&#36733;&#38378;&#36864;</p>
"},
     "observers": [
 
     ]
 }
 ```

**Comment by kotomei** [comment]
## Application information
 - Package name: `de.robv.android.xposed.installer`
 - Display name: Xposed Installer
 - Version: 3.1.4 by dvdandroid - 25/12/17 (41)
 ## User rules
 - `recommended`: Yes
 - `need_appops`: No
 - `feature_affected`: No
 - Reason: 该应用会在非标准位置创建文件和文件夹。<br>开启重定向（配合链接规则）<b>不影响该应用的使用效果</b>。
 ### ObserverInfo
 #### Directory: `Android/data/de.robv.android.xposed.installer/cache/downloads/modules`
 - `description`: `下载的 Xposed 模组文件`

 ## More information
 - Android version: 8.0.0 (API 26)
 - User language: en_US
 - Storage Redirect app version: 0.9.0-alpha.r274.8423e60 (274)
 ## JSON Output
 ```
 {
     "package": "de.robv.android.xposed.installer",
     "recommended": true,
     "need_appops": false,
     "feature_affected": false,
     "authors": ["kotomei"],
     "reason": {"default": "该应用会在非标准位置创建文件和文件夹。<br>开启重定向（配合链接规则）<b>不影响该应用的使用效果</b>。"},
     "observers": [
         {
             "description": "下载的 Xposed 模组文件",
             "source": "Android/data/de.robv.android.xposed.installer/cache/downloads/modules"
         }
     ]
 }
 ```

**Comment by wyy8087** [comment]
## Application information
 - Package name: `de.robv.android.xposed.installer`
 - Display name: Xposed Installer
 - Version: 3.1.5 (43)
 ## User rules
 - `recommended`: No
 - `need_appops`: No
 - `feature_affected`: No
 - Reason: <p dir="ltr">&#35813;&#24212;&#29992;<b>&#27809;&#26377;&#38750;&#26631;&#20934;&#34892;&#20026;</b>&#12290;<br>
&#24320;&#21551;&#37325;&#23450;&#21521;&#21453;&#32780;&#21487;&#33021;&#20250;<b>&#24433;&#21709;&#35813;&#24212;&#29992;&#30340;&#27491;&#24120;&#34892;&#20026;</b>&#12290;</p>

 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.9.0-alpha.r274.8423e60 (274)
 ## JSON Output
 ```
 {
     "package": "de.robv.android.xposed.installer",
     "recommended": false,
     "need_appops": false,
     "feature_affected": false,
     "authors": ["wyy8087"],
     "reason": {"default": "<p dir="ltr">&#35813;&#24212;&#29992;<b>&#27809;&#26377;&#38750;&#26631;&#20934;&#34892;&#20026;</b>&#12290;<br>
&#24320;&#21551;&#37325;&#23450;&#21521;&#21453;&#32780;&#21487;&#33021;&#20250;<b>&#24433;&#21709;&#35813;&#24212;&#29992;&#30340;&#27491;&#24120;&#34892;&#20026;</b>&#12290;</p>
"},
     "observers": [
 
     ]
 }
 ```

**Comment by Exeedy** [comment]
When you install the modules with root it won't install the apk file if its redirected.

**Comment by yiheng0** [comment]
## Application information
 - Package name: `de.robv.android.xposed.installer`
 - Display name: Xposed Installer
 - Version: 3.1.5 (43)
 ## User rules
 - `recommended`: No
 - `need_appops`: No
 - `feature_affected`: Yes
 - Reason: <p dir="ltr">&#35813;&#24212;&#29992;&#20250;&#22312;&#38750;&#26631;&#20934;&#20301;&#32622;&#21019;&#24314;&#25991;&#20214;&#21644;&#25991;&#20214;&#22841;&#12290;<br>
&#20294;&#22312;&#24320;&#21551;&#37325;&#23450;&#21521;&#21518;&#20250;&#24433;&#21709;&#33258;&#21160;&#21047;&#20837;xposed&#21253;&#21151;&#33021;</p>

 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.1.1 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.9.0-alpha.r274.8423e60 (274)
 ## JSON Output
 ```
 {
     "package": "de.robv.android.xposed.installer",
     "recommended": false,
     "need_appops": false,
     "feature_affected": true,
     "authors": ["yiheng0"],
     "reason": {"default": "<p dir="ltr">&#35813;&#24212;&#29992;&#20250;&#22312;&#38750;&#26631;&#20934;&#20301;&#32622;&#21019;&#24314;&#25991;&#20214;&#21644;&#25991;&#20214;&#22841;&#12290;<br>
&#20294;&#22312;&#24320;&#21551;&#37325;&#23450;&#21521;&#21518;&#20250;&#24433;&#21709;&#33258;&#21160;&#21047;&#20837;xposed&#21253;&#21151;&#33021;</p>
"},
     "observers": [
 
     ]
 }
 ```
