### ISSUE TITLE
[New rules request][AUTO] taipei.sean.telegram.plus

### ISSUE THREAD

**Issue by YHNdnzj** [RikkaW/RedirectStorage-rules#227]
## Application information
 - Package name: `taipei.sean.telegram.plus`
 - Display name: Telegreat
 - Version: 4.2.1.1 (10485)
 ## User rules
 - `recommended`: Yes
 - `need_appops`: No
 - `feature_affected`: Yes
 - Reason: <p dir="ltr">Telegram &#20013;&#30340;&#30332;&#36865;&#27284;&#26696;&#21151;&#33021;&#28961;&#27861;&#20351;&#29992;</p>

 ### ObserverInfo
 #### Directory: `Telegram/Telegram Audio`
 - `description`: `儲存的音頻`
#### Directory: `Telegram/Telegram Documents`
 - `description`: `儲存的文檔`
#### Directory: `Telegram/Telegram Images`
 - `description`: `儲存的圖片`
#### Directory: `Telegram/Telegram Video`
 - `description`: `儲存的視頻`

 ## More information
 - Android version: 8.1.0 (API 27)
 - User language: zh_TW_#Hant
 - Storage Redirect app version: 0.9.0-alpha.r274.8423e60 (274)
 ## JSON Output
 ```
 {
     "package": "taipei.sean.telegram.plus",
     "recommended": true,
     "need_appops": false,
     "feature_affected": true,
     "authors": ["YHNdnzj"],
     "reason": {"default": "<p dir="ltr">Telegram &#20013;&#30340;&#30332;&#36865;&#27284;&#26696;&#21151;&#33021;&#28961;&#27861;&#20351;&#29992;</p>
"},
     "observers": [
         {
             "description": "儲存的音頻",
             "source": "Telegram/Telegram Audio"
         },
         {
             "description": "儲存的文檔",
             "source": "Telegram/Telegram Documents"
         },
         {
             "description": "儲存的圖片",
             "source": "Telegram/Telegram Images"
         },
         {
             "description": "儲存的視頻",
             "source": "Telegram/Telegram Video"
         }
     ]
 }
 ```

**Comment by RikkaW** [comment]
Files in `/Telegram` are treated as cache files (for example images in `Telegram/Telegram Images` are not shown in gallery app) by Telegram app, so it's meaningless to link these files to outside.
