### ISSUE TITLE
[New rules request][AUTO] info.papdt.express.helper

### ISSUE THREAD

**Issue by kotomei** [RikkaW/RedirectStorage-rules#233]
## Application information
 - Package name: `info.papdt.express.helper`
 - Display name: Package Tracker
 - Version: 3.1.0 (52)
 ## User rules
 - `recommended`: No
 - `need_appops`: No
 - `feature_affected`: No
 - Reason: 该应用<b>没有非标准行为</b>。<br>开启重定向反而可能会<b>影响该应用的正常行为</b>。
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 8.0.0 (API 26)
 - User language: en_US
 - Storage Redirect app version: 0.9.0-alpha.r274.8423e60 (274)
 ## JSON Output
 ```
 {
     "package": "info.papdt.express.helper",
     "recommended": false,
     "need_appops": false,
     "feature_affected": false,
     "authors": ["kotomei"],
     "reason": {"default": "该应用<b>没有非标准行为</b>。<br>开启重定向反而可能会<b>影响该应用的正常行为</b>。"},
     "observers": [
 
     ]
 }
 ```

**Comment by Sherlock-Holo** [comment]
## Application information
 - Package name: `info.papdt.express.helper`
 - Display name: 水表助手
 - Version: 3.1.0 (52)
 ## User rules
 - `recommended`: No
 - `need_appops`: No
 - `feature_affected`: No
 - Reason: 该应用<b>没有非标准行为</b>。<br>开启重定向反而可能会<b>影响该应用的正常行为</b>。
 ### ObserverInfo
 No observers.
 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_CN_#Hans
 - Storage Redirect app version: 0.9.0-alpha.r274.8423e60 (274)
 ## JSON Output
 ```
 {
     "package": "info.papdt.express.helper",
     "recommended": false,
     "need_appops": false,
     "feature_affected": false,
     "authors": ["Sherlock-Holo"],
     "reason": {"default": "该应用<b>没有非标准行为</b>。<br>开启重定向反而可能会<b>影响该应用的正常行为</b>。"},
     "observers": [
 
     ]
 }
 ```
