### ISSUE TITLE
我觉得HOW TO文档可以再详细点

### ISSUE THREAD

**Issue by Yamiku** [RikkaW/RedirectStorage-rules#26]
一些配置的作用还是看不懂

**Comment by FoobarRogers** [comment]
说说看哪些有难度

**Comment by fython** [comment]
新版仓库已转移到 [RikkaApps/StorageRedirect-assets](https://github.com/RikkaApps/StorageRedirect-assets)，如需继续讨论，请在新仓库新建 Issues，并简要指出需要改进的地方。
