### ISSUE TITLE
[New rules request][AUTO] com.whatsapp

### ISSUE THREAD

**Issue by Annshion** [RikkaW/RedirectStorage-rules#284]
## Application information
 - Package name: `com.whatsapp`
 - Display name: WhatsApp
 - Version: 2.18.29 (452151)
 ## User rules
 - `recommended`: Yes
 - `need_appops`: No
 - `feature_affected`: No
 - Reason: 该应用会在非标准位置创建文件和文件夹。<br>开启重定向（配合链接规则）<b>不影响该应用的使用效果</b>。
 ### ObserverInfo
 #### Directory: `WhatsApp/Media/WhatsApp Images`
 - `description`: `保存的图片`

 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.9.0-alpha.r274.8423e60 (274)
 ## JSON Output
 ```
 {
     "package": "com.whatsapp",
     "recommended": true,
     "need_appops": false,
     "feature_affected": false,
     "authors": ["Annshion"],
     "reason": {"default": "该应用会在非标准位置创建文件和文件夹。<br>开启重定向（配合链接规则）<b>不影响该应用的使用效果</b>。"},
     "observers": [
         {
             "description": "保存的图片",
             "source": "WhatsApp/Media/WhatsApp Images"
         }
     ]
 }
 ```

**Comment by fython** [comment]
I guess this rule is not completed enough. Wait for more comments.
