### ISSUE TITLE
[New rules request][AUTO] com.sing.client

### ISSUE THREAD

**Issue by Eraktty** [RikkaW/RedirectStorage-rules#332]
## Application information
 - Package name: `com.sing.client`
 - Display name: 5sing原创音乐
 - Version: 6.6.3.2 (66320)
 ## User rules
 - `recommended`: Yes
 - `need_appops`: No
 - `feature_affected`: Yes
 - Reason: 该应用会在非标准位置创建文件和文件夹。<br>但需要注意，开启重定向后<b>该应用的一些功能可能会无法使用</b>。
 ### ObserverInfo
 #### Directory: `5sing`
 - `description`: `下载的音乐`

 ## More information
 - Android version: 7.0 (API 24)
 - User language: zh_CN_#Hans
 - Storage Redirect app version: 0.9.0-alpha.r274.8423e60 (274)
 ## JSON Output
 ```
 {
     "package": "com.sing.client",
     "recommended": true,
     "need_appops": false,
     "feature_affected": true,
     "authors": ["Eraktty"],
     "reason": {"default": "该应用会在非标准位置创建文件和文件夹。<br>但需要注意，开启重定向后<b>该应用的一些功能可能会无法使用</b>。"},
     "observers": [
         {
             "description": "下载的音乐",
             "source": "5sing"
         }
     ]
 }
 ```

**Comment by qylmr4621** [comment]
## Application information
 - Package name: `com.sing.client`
 - Display name: 5sing原创音乐
 - Version: 6.6.3.2 (66320)
 ## User rules
 - `recommended`: Yes
 - `need_appops`: No
 - `feature_affected`: Yes
 - Reason: <p dir="ltr">&#35813;&#24212;&#29992;&#20250;&#22312;&#38750;&#26631;&#20934;&#20301;&#32622;&#21019;&#24314;&#25991;&#20214;&#21644;&#25991;&#20214;&#22841;&#12290;<br>
&#24320;&#21551;&#37325;&#23450;&#21521;&#65288;&#37197;&#21512;&#38142;&#25509;&#35268;&#21017;&#65289;<b>&#19981;&#24433;&#21709;&#35813;&#24212;&#29992;&#30340;&#20351;&#29992;&#25928;&#26524;</b>&#12290;</p>

 ### ObserverInfo
 #### Directory: `5sing/download`
 - `description`: `保存的音乐`

 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_CN_#Hans
 - Storage Redirect app version: 0.9.0-alpha.r274.8423e60 (274)
 ## JSON Output
 ```
 {
     "package": "com.sing.client",
     "recommended": true,
     "need_appops": false,
     "feature_affected": true,
     "authors": ["qylmr4621"],
     "reason": {"default": "<p dir="ltr">&#35813;&#24212;&#29992;&#20250;&#22312;&#38750;&#26631;&#20934;&#20301;&#32622;&#21019;&#24314;&#25991;&#20214;&#21644;&#25991;&#20214;&#22841;&#12290;<br>
&#24320;&#21551;&#37325;&#23450;&#21521;&#65288;&#37197;&#21512;&#38142;&#25509;&#35268;&#21017;&#65289;<b>&#19981;&#24433;&#21709;&#35813;&#24212;&#29992;&#30340;&#20351;&#29992;&#25928;&#26524;</b>&#12290;</p>
"},
     "observers": [
         {
             "description": "保存的音乐",
             "source": "5sing/download"
         }
     ]
 }
 ```
