### ISSUE TITLE
[New rules request][AUTO] com.xunlei.downloadprovider

### ISSUE THREAD

**Issue by LoIIipop** [RikkaW/RedirectStorage-rules#345]
Application information
• Package name: com.xunlei.downloadprovider 
• Display name: 迅雷
• Version: 5.54.2.5330

User rules
•  recommended : Yes
•  need_appops : No
•  feature_affected : No
• Reason: 该应用会在非标准位置创建文件和文件夹。
开启重定向（配合链接规则） 不影响该应用的使用效果 。

ObserverInfo

Directory: Android/obb/com.xunlei.downloadprovider 
•  description : 下载的文件 

More information
• Android version: 8.1 (API 27)
• User language: zh_CN_#Hans
• Storage Redirect app version: 0.12.3-beta.r501.6e61bc0

JSON Output

{
    "package": "com.xunlei.downloadprovider",
    "recommended": true,
    "need_appops": false,
    "feature_affected": false,
    "authors": ["eatmang0"],
    "reason": {"default": "该应用会在非标准位置创建文件和文件夹。<br>开启重定向（配合链接规则）<b>不影响该应用的使用效果</b>。"},
    "observers": [
        {
            "description": "下载的文件",
            "source": "Android/obb/com.xunlei.downloadprovider"
        }
    ]
}

**Comment by fython** [comment]
@LoIIipop 请使用新版默认的仓库位置。
