### ISSUE TITLE
[New rules request][AUTO] com.keramidas.TitaniumBackup

### ISSUE THREAD

**Issue by simonsmh** [RikkaW/RedirectStorage-rules#47]
## Application information
 - Package name: `com.keramidas.TitaniumBackup`
 - Display name: 钛备份
 - Version: 8.1.0 (397)
 ## User rules
 - `recommended`: Yes
 - `need_appops`: No
 - `feature_affected`: Yes
 ### ObserverInfo
 #### Directory: `TitaniumBackup`
 - `description`: `钛备份备份文件`

 ## More information
 - Android version: 8.0.0 (API 26)
 - User language: zh_CN_#Hans
 - Storage Redirect app version: 0.7.2-alpha.r145.04287ea (145)
 ## JSON Output
 ```
 {
     "package": "com.keramidas.TitaniumBackup",
     "recommended": true,
     "need_appops": false,
     "feature_affected": true,
     "authors": [],
     "observers": [
         {
             "description": "钛备份备份文件",
             "source": "TitaniumBackup"
         }
     ]
 }
 ```

**Comment by FoobarRogers** [comment]
钛备份不是可以修改目录嘛

**Comment by simonsmh** [comment]
pro拉了坨data的shit

**Comment by FoobarRogers** [comment]
@simonsmh也就是说你是不希望data文件夹出现喽

**Comment by HYHYatt** [comment]
## Application information
 - Package name: `com.keramidas.TitaniumBackup`
 - Display name: 钛备份
 - Version: 8.1.0 (397)
 ## User rules
 - `recommended`: Yes
 - `need_appops`: No
 - `feature_affected`: No
 ### ObserverInfo
 #### Directory: `TitaniumBackup`
 - `description`: `备份文件`

 ## More information
 - Android version: 7.1.1 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.7.6-alpha.r168.eb6a367 (168)
 ## JSON Output
 ```
 {
     "package": "com.keramidas.TitaniumBackup",
     "recommended": true,
     "need_appops": false,
     "feature_affected": false,
     "authors": [],
     "observers": [
         {
             "description": "备份文件",
             "source": "TitaniumBackup"
         }
     ]
 }
 ```
