### ISSUE TITLE
[New rules request][AUTO] com.fooview.android.fooview

### ISSUE THREAD

**Issue by monkey-sking** [RikkaW/RedirectStorage-rules#56]
## Application information
 - Package name: `com.fooview.android.fooview`
 - Display name: fooView
 - Version: 0.8.8.6_arm (77)
 ## User rules
 - `recommended`: No
 - `need_appops`: No
 - `feature_affected`: No
 ### ObserverInfo
 #### Directory: `Download`
 - `description`: `下载目录`

 ## More information
 - Android version: 8.0.0 (API 26)
 - User language: zh_CN_#Hans
 - Storage Redirect app version: 0.7.2-alpha.r145.04287ea (145)
 ## JSON Output
 ```
 {
     "package": "com.fooview.android.fooview",
     "recommended": false,
     "need_appops": false,
     "feature_affected": false,
     "authors": [],
     "observers": [
         {
             "description": "下载目录",
             "source": "Download"
         }
     ]
 }
 ```

**Comment by FoobarRogers** [comment]
fooview可以在设置里面修改，不需要特地弄一个
