### ISSUE TITLE
[New rules request][AUTO] com.hippo.ehviewer

### ISSUE THREAD

**Issue by FoobarRogers** [RikkaW/RedirectStorage-rules#64]
## Application information
 - Package name: `com.hippo.ehviewer`
 - Display name: EhViewer
 - Version: 1.0.25 (78)
 ## User rules
 - `recommended`: Yes
 - `need_appops`: No
 - `feature_affected`: No
 ### ObserverInfo
 #### Directory: `EhViewer/download`
 - `description`: `ehentai图片`

 ## More information
 - Android version: 8.0.0 (API 26)
 - User language: zh_CN
 - Storage Redirect app version: 0.7.3-alpha.r158.f6d9a1a (158)
 ## JSON Output
 ```
 {
     "package": "com.hippo.ehviewer",
     "recommended": true,
     "need_appops": false,
     "feature_affected": false,
     "authors": [],
     "observers": [
         {
             "description": "ehentai图片",
             "source": "EhViewer/download"
         }
     ]
 }
 ```

**Comment by fython** [comment]
emmm... I think `recommended` should be `false`.
