### ISSUE TITLE
[New rules request][AUTO] com.taptap

### ISSUE THREAD

**Issue by zhou1012** [RikkaW/RedirectStorage-rules#75]
## Application information
 - Package name: `com.taptap`
 - Display name: TapTap
 - Version: 1.9.8 (321)
 ## User rules
 - `recommended`: Yes
 - `need_appops`: No
 - `feature_affected`: No
 ### ObserverInfo
 #### Directory: `Android/data/com.taptap/files/Download/taptaptmp`
 - `description`: `下载`

 ## More information
 - Android version: 7.1.2 (API 25)
 - User language: zh_CN
 - Storage Redirect app version: 0.7.2-alpha.r145.04287ea (145)
 ## JSON Output
 ```
 {
     "package": "com.taptap",
     "recommended": true,
     "need_appops": false,
     "feature_affected": false,
     "authors": [],
     "observers": [
         {
             "description": "下载",
             "source": "Android/data/com.taptap/files/Download/taptaptmp"
         }
     ]
 }
 ```

**Comment by fython** [comment]
存在 `Android/data` 的文件感觉没有必要移出来，但作为可选项好像也行。

**Comment by FoobarRogers** [comment]
@fython这个是原本应该在DCIM/jdimage的文件

**Comment by FoobarRogers** [comment]
@zhou1012描述一下这个文件夹的作用

**Comment by fython** [comment]
@FoobarRogers 足够了。
